### PR TITLE
[wip] reconnect after connection drop

### LINKED ISSUE #1: Lib doesn't reconnect
The connection might close undetected, throwing this error when trying to send requests: `Error: WebSocket is not open: readyState 3 (CLOSED)`.

### PR DESCRIPTION
**Pull request by askmike**
fixes #1.

### CODE REVIEW

**Comment by abhishekgahlot** [comment]
@askmike I am planning to use this library, Is this PR tested, I can help in this as well.

**Comment by askmike** [comment]
It's being tested: the problem with the deribit websocket is that it's very stable. I'm running this code right now and have been for days but haven't encountered another disconnect since #1.

**Comment by PrimeDominus** [comment]
Doesn't seem like a bad "problem" to have 🙂

**Comment by askmike** [comment]
Definitely not! But I haven't been able to test this properly.

This current retry logic is a bit messy, would be better to refactor the whole thing into a class (per connection).

**Comment by askmike** [comment]
@abhishekgahlot @PrimeDominus @mike0xff

The code on master prior to merging didn't handle reconnect at all, the initial reconnect code (
1a93b79) was buggy so I refactored everything into a connection class. Note the API has slightly changed, see example.js.

**Pull request merged**
