### PR TITLE
Clear InflightQueue and reject pending promises on connection failure before reconnect

### PR DESCRIPTION
**Pull request by lacksfish**
When closing a connection (due to error or otherwise) pending request promises should possibly be rejected, otherwise they might end up `await`ing for eternity which might cause undesired side effects.

To my understanding, those pending requests will not get resolved after a reconnect, so it is better to reject them once the connection is dropped.

### CODE REVIEW

**Comment by askmike** [comment]
Woow this is awesome, I was expecting a leak but wasn't able to find it. This might very well be it.

One nit: would you mind passing an error to that connectionAborted call? Such as `new Error("Deribit connection closed.")`? Thanks!

**Comment by lacksfish** [comment]
`new Error` added, rebased and force-pushed. You're welcome. :)

**Comment by askmike** [comment]
Thanks!

**Comment by askmike** [comment]
Published in `deribit-v2-ws@1.0.6`.

**Pull request merged**
