### PR TITLE
Add Babel to transpile project to ES5

### PR DESCRIPTION
**Pull request by lacksfish**
To transpile to ES5 (which every browser and `node` of older versions understand) just run:

`npm run build-es5`

### CODE REVIEW

**Comment by askmike** [comment]
This project unfortunately won't work in a browser (since it uses node specific APIs like the node EventEmitter. It does work in new version of Nodejs. Which version did you encounter problems with?

**Comment by askmike** [comment]
I'm asking because babel adds a ton of packages whenever any dev downloads this and does a `npm install`.

**Comment by askmike** [comment]
I'd recommend people who want this to fork this lib or so. I'm not going to pollute the dependency graph for the sake of people running old versions of nodejs :(

**Comment by lacksfish** [comment]
Understood, it would be useful so that users of this lib can use it in their websites to (for example) retrieve data from public endpoints.

**Comment by lacksfish** [comment]
But I overlooked that there are other node specific dependencies, as you mentioned. Therefore my point is kind of moot. Thanks for the awesome lib, either way! :+1:

**Comment by askmike** [comment]
Thanks :)

**Pull request closed without merging**
